/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http.stress.mci.test;



public class App {


    public static void main(String[] args)   {
         new StressManager();

    }
}
